import './globals.css'
import { Montserrat } from 'next/font/google'
import { Fira_Mono } from 'next/font/google'

import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { Toaster } from '@/components/ui/Toaster'

const mont = Montserrat({
  weight: '400',
  variable: '--font-mont',
  subsets: ['latin'],
})
const fira = Fira_Mono({
  weight: '400',
  variable: '--font-fira',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${mont.variable} ${fira.variable} overflow-x-hidden relative`}
      >
        <Navbar />
        {children}
        <Footer />
        <Toaster />
      </body>
    </html>
  )
}
